### ISSUE TITLE
Released version does not install

### ISSUE THREAD

**Issue by madleech** [demchenkoe/node-wiring-op#6]
Hi there, the released version does not install on an OrangePI lite. Output:

```
$ npm install wiring-op
|
> wiring-op@2.1.1 install /tmp/node_modules/wiring-op
> /bin/bash ./install.sh

Cloning libWiringPi ... done.
patching file ./wiringpi/devLib/Makefile
Hunk #2 FAILED at 34.
1 out of 2 hunks FAILED -- saving rejects to file ./wiringpi/devLib/Makefile.rej
patching file ./wiringpi/gpio/Makefile
Making libWiringPi ... done.
Making devLib ...done.
Unistalling gpio utility ... done.
Making gpio utility ... done.
Installing gpio utility ... done.
Making wiring-pi ... make: Entering directory '/tmp/node_modules/wiring-op/build'
  CXX(target) Release/obj.target/wiringPi/src/addon.o
  CXX(target) Release/obj.target/wiringPi/src/wiringPi.o
  CXX(target) Release/obj.target/wiringPi/src/softPwm.o
  CXX(target) Release/obj.target/wiringPi/src/softServo.o
  CXX(target) Release/obj.target/wiringPi/src/softTone.o
  CXX(target) Release/obj.target/wiringPi/src/wiringPiI2C.o
  CXX(target) Release/obj.target/wiringPi/src/wiringPiSPI.o
../src/wiringPiSPI.cc: In function ‘void nodemodule::wiringPiSPISetupMode(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/wiringPiSPI.cc:90:7: warning: unused variable ‘speed’ [-Wunused-variable]
   int speed = GET_ARGUMENT_AS_INT32(1);
       ^
  CXX(target) Release/obj.target/wiringPi/src/wiringSerial.o
  CXX(target) Release/obj.target/wiringPi/src/wiringShift.o
  CXX(target) Release/obj.target/wiringPi/src/wiringPiISR.o
  CXX(target) Release/obj.target/wiringPi/src/wpi.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/extensions.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/drcSerial.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/max5322.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/max31855.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/mcp23s08.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/mcp23s17.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/mcp3002.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/mcp3004.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/mcp3422.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/mcp4802.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/mcp23008.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/mcp23016.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/mcp23017.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/pcf8574.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/pcf8591.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/sn3218.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/sr595.o
  CXX(target) Release/obj.target/wiringPi/src/extensions/pca9685.o
../src/extensions/pca9685.cc:2:21: fatal error: pca9685.h: No such file or directory
 #include <pca9685.h>
                     ^
compilation terminated.
wiringPi.target.mk:137: recipe for target 'Release/obj.target/wiringPi/src/extensions/pca9685.o' failed
make: *** [Release/obj.target/wiringPi/src/extensions/pca9685.o] Error 1
make: Leaving directory '/tmp/node_modules/wiring-op/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.4.112-sun8i
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/node_modules/wiring-op
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
done.
Enjoy !
wiring-op@2.1.1 node_modules/wiring-op
```

However the patches in https://github.com/molda/node-wiring-op work great.

**Comment by DaniyalGeek** [comment]
same issue

**Comment by keysim** [comment]
Same. I'm using orange pi PC. Please help us ! =)

**Comment by justin-romano** [comment]
Same.

**Comment by klemens79** [comment]
I created a pull request, which fixes this issue!
